version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development
      - typo3DatabaseDriver=pdo_mysql
      - typo3DatabaseHost=db
      - typo3DatabaseName=db
      - typo3DatabaseUsername=root
      - typo3DatabasePassword=root
      - PHP_IDE_CONFIG=serverName=t3-messenger.ddev.site
