name: Tests

on:
    pull_request: null
    push:
        branches:
            - 'main'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                typo3-versions:
                    - { typo3: ^13.4, testing: ^9, php: 8.2 }
                    - { typo3: ^13.4, testing: ^9, php: 8.3 }
                    - { typo3: ^13.4, testing: ^9, php: 8.4 }

        name: "Run tests with PHP ${{ matrix.typo3-versions.php }}
                  using TYPO3 ${{ matrix.typo3-versions.typo3 }}
                  with testing framework version ${{ matrix.typo3-versions.testing }}"
        steps:
            -   uses: actions/checkout@v5

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.typo3-versions.php }}"
                    extensions: intl, mbstring, pdo_sqlite, pdo_mysql
                    tools: composer:v2
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Start MySQL
              run: sudo /etc/init.d/mysql start

            - name: Run composer require
              run: "composer require typo3/testing-framework:${{ matrix.typo3-versions.testing }} typo3/cms-core:${{ matrix.typo3-versions.typo3 }}"

            # see https://github.com/ramsey/composer-install
            - uses: "ramsey/composer-install@v3"

            - name: "Run Unit tests"
              run: composer test-unit

            - name: "Functional tests"
              run: |
                export typo3DatabaseName="typo3";
                export typo3DatabaseHost="127.0.0.1";
                export typo3DatabaseUsername="root";
                export typo3DatabasePassword="root";
                composer test-functional
